---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Login to OpenShift
      shell: |
        oc login $OPENSHIFT_SERVER \
        --token=$OPENSHIFT_TOKEN \
        --insecure-skip-tls-verify

    - name: Select project
      shell: |
        oc project mounika-red-dev

    - name: Verify deployment
      shell: |
        oc get deployment myfirstd -n mounika-red-dev

    - name: Verify pods
      shell: |
        oc get pods -n mounika-red-dev

    - name: Verify service
      shell: |
        oc get svc -n mounika-red-dev

    - name: Verify route
      shell: |
        oc get route -n mounika-red-dev

    - name: Check rollout status
      shell: |
        oc rollout status deployment/myfirstd -n mounika-red-dev

    - name: Get application URL
      shell: |
        oc get route myfirstd-route \
        -n mounika-red-dev \
        --template='{{ .spec.host }}'
