---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Login to OpenShift
      shell: |
        oc login $OPENSHIFT_SERVER \
        --token=$OPENSHIFT_TOKEN \
        --insecure-skip-tls-verify

    - name: Select project
      shell: |
        oc project mounika-red-dev

    - name: Deploy application
      shell: |
        oc apply -f deployment.yaml -n mounika-red-dev

    - name: Verify pods
      shell: |
        oc get pods -n mounika-red-dev
