apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myfirstd-monitor
  namespace: dev

spec:
  selector:
    matchLabels:
      app: myfirstd

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
