namespace: mounika-red-dev

app_name: my-app

image: image-registry.openshift-image-registry.svc:5000/mounika-red-dev/my-app:{{ lookup('env','IMAGE_TAG') }}
route_host: my-app-mounika-red-dev.apps.rm1.0a51.p1.openshiftapps.com
