name: Full DevOps Pipeline

on:
  push:
    branches:
      - New

jobs:

  terraform:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version
        
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

  ansible:

    needs: terraform

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run Playbook
        run: ansible-playbook deploy.yml
