#deleting the file
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Delete Docker Image Tag
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

        echo "🔐 Logging into Docker Hub..."

        RESPONSE=$(curl -s -X POST "https://hub.docker.com/v2/users/login/" -H "Content-Type: application/json" -d '{"username": "'"${{ secrets.DOCKER_USERNAME }}"'","password": "'"${{ secrets.DOCKER_PASSWORD }}"'"}')

        echo "Login Response: $RESPONSE"

        TOKEN=$(echo "$RESPONSE" | jq -r '.token')

        if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
        echo "❌ Failed to get token"
        exit 1
        fi

        echo "✅ Token received"
        echo "✅ Fetching all tags..."

        TAGS=$(curl -s -H "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/my-app/tags?page_size=100" | jq -r '.results[].name')

        echo "Tags found:"
        echo "$TAGS"

        for TAG in $TAGS; do
        echo "🗑️ Deleting tag: $TAG"

        echo "🗑️ Deleting tag..."

        STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \ -H "Authorization: JWT $TOKEN" \ "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/my-app/tags/$TAG/")

        echo "HTTP Status: $STATUS"
        cat delete_response.txt

        if [ "$STATUS" != "204" ]; then
        echo "❌ Delete failed"
        exit 1
        fi

        echo "✅ Tag deleted successfully"

